Use strlcpy instead of strncpy
On Debian, it will report as below:
native/syscalls.c:864:22: error: passing argument 2 of ‘strncpy’ from incompatible pointer type [-Wincompatible-pointer-types]
  864 |         strncpy(buf, &address_->sun_path, 108);
      |                      ^~~~~~~~~~~~~~~~~~~
      |                      |
      |                      char (*)[108]

Signed-off-by: Bo YU <tsu.yubo@gmail.com>